version: "3.9"

services:
  app:
    image: gotodo
    build:
      args:
        - target=dev #ビルドステージの指定
    environment:
      - TODO_ENV=dev
      - PORT=8080
    volumes:
      - .:/app
    ports:
      - "18080:18080"
